"""permissions

Revision ID: 2ed4063cf1db
Revises: 88e228c72788
Create Date: 2025-11-24 14:22:22.766719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2ed4063cf1db'
down_revision: Union[str, Sequence[str], None] = '88e228c72788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
permission_enum = postgresql.ENUM(
    'ALL_PERMISSIONS', 'READ_ORGANIZATION', 'WRITE_ORGANIZATION',
    'READ_ORG_SETTINGS', 'WRITE_ORG_SETTINGS', 'READ_CONTACT', 'WRITE_CONTACT', 'DELETE_CONTACT',
    'READ_DEAL', 'WRITE_DEAL', 'DELETE_DEAL',
    'READ_TASK', 'WRITE_TASK', 'DELETE_TASK',
    name='permission'
)
permission_enum.create(op.get_bind())

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_member_permissions', 'permission',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ALL_PERMISSIONS', 'READ_ORGANIZATION', 'WRITE_ORGANIZATION', 'READ_ORG_SETTINGS', 'WRITE_ORG_SETTINGS', 'READ_CONTACT', 'WRITE_CONTACT', 'DELETE_CONTACT', 'READ_DEAL', 'WRITE_DEAL', 'DELETE_DEAL', 'READ_TASK', 'WRITE_TASK', 'DELETE_TASK', name='permission'),
               existing_nullable=False, postgresql_using="permission::permission")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_member_permissions', 'permission',
               existing_type=sa.Enum('ALL_PERMISSIONS', 'READ_ORGANIZATION', 'WRITE_ORGANIZATION', 'READ_ORG_SETTINGS', 'WRITE_ORG_SETTINGS', 'READ_CONTACT', 'WRITE_CONTACT', 'DELETE_CONTACT', 'READ_DEAL', 'WRITE_DEAL', 'DELETE_DEAL', 'READ_TASK', 'WRITE_TASK', 'DELETE_TASK', name='permission'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
