"""fix OrganizationMemberModel

Revision ID: 5cde00b9a287
Revises: 2ed4063cf1db
Create Date: 2025-11-24 14:32:07.634302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cde00b9a287'
down_revision: Union[str, Sequence[str], None] = '2ed4063cf1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
